# Generated by Django 4.0.5 on 2022-06-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=150)),
                ('content_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=35)),
                ('tags_projects', models.ManyToManyField(through='main.ProjectTag', to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag', verbose_name=''),
        ),
    ]
